export function buildCodeGenerationPrompt({ specification, blueprint, previousFiles, targetFiles, contracts, warnings, agentName, phase, dependencyContext }) {
  return [
    'You are ' + (agentName || 'Code Generation Agent') + ', generating complete files for a frontend-only React Vite application.',
    '',
    'Return strict JSON only. Do not include Markdown fences.',
    '',
    'Current dependency-ordered phase: ' + (phase || 'code_generation'),
    '',
    'Frontend Manager DAG:',
    '- Frontend Manager Agent orchestrates all phases.',
    '- Project Setup Agent creates React/Vite/Tailwind foundation.',
    '- Component Agent builds shared components and reusable contracts.',
    '- Layout Agent consumes registered components to build shell/navigation/routing.',
    '- Page Agent and Styling Agent may run concurrently after layout because they only consume registered components/layouts/tokens.',
    '- Final integration assembles React project files.',
    '',
    'Allowed generated project stack:',
    '- React.js with Vite',
    '- JavaScript',
    '- Tailwind CSS',
    '- React Router when useful',
    '- Redux Toolkit only when useful',
    '- Lucide React',
    '- localStorage',
    '- Mock data',
    '- Frontend-only mock flows for payments, auth, uploads, email, maps, analytics, or third-party integrations unless the package is already in the allowed stack',
    '',
    'Disallowed: Express, MongoDB, Mongoose, SQL, authentication, JWT, OAuth, Docker, Next.js, server routes, server-only secrets.',
    'Do not import random external SDKs for requested product features. For example, if the user asks for Stripe/payment UI, build a frontend mock checkout flow with local state and mock data unless the requested target file is package.json and the dependency is explicitly supported.',
    '',
    'Return this exact JSON shape:',
    '{ "files": [{ "path": "src/components/Header.jsx", "language": "jsx", "content": "complete file content" }], "contracts": [], "warnings": [] }',
    '',
    'Generate only the requested target files. Preserve exact paths. Return complete working file contents. Do not use placeholder comments or TODO-only code. Ensure imports refer to generated or existing files.',
    'Never import a relative module unless that exact file exists in previous files, target files, or the blueprint file list. If you import ./routes/AppRoutes, then src/routes/AppRoutes.jsx must be generated or already present.',
    'Respect dependency order: consume previous files/contracts, but do not redefine upstream responsibilities unless a requested target file requires it.',
    '',
    'Specification:',
    JSON.stringify(specification, null, 2),
    '',
    'Blueprint:',
    JSON.stringify(blueprint, null, 2),
    '',
    'Previously generated files:',
    JSON.stringify(previousFiles?.map((file) => ({ path: file.path, language: file.language })), null, 2),
    '',
    'Target files:',
    JSON.stringify(targetFiles, null, 2),
    '',
    'Registered contracts:',
    JSON.stringify(contracts || [], null, 2),
    '',
    'Dependency context:',
    JSON.stringify(dependencyContext || {}, null, 2),
    '',
    'Known pitfalls to avoid from verified fix memory:',
    dependencyContext?.knownPitfalls || 'No verified pitfalls matched this context.',
    '',
    'Previous warnings:',
    JSON.stringify(warnings || [], null, 2)
  ].join('\n');
}
