export function buildCodeGenerationPrompt({ specification, blueprint, previousFiles, targetFiles, contracts, warnings }) {
  return [
    'You are generating complete files for a frontend-only React Vite application.',
    '',
    'Return strict JSON only. Do not include Markdown fences.',
    '',
    'Allowed generated project stack:',
    '- React.js with Vite',
    '- JavaScript',
    '- Tailwind CSS',
    '- React Router when useful',
    '- Redux Toolkit only when useful',
    '- Lucide React',
    '- localStorage',
    '- Mock data',
    '',
    'Disallowed: Express, MongoDB, Mongoose, SQL, authentication, JWT, OAuth, Docker, Next.js, server routes, server-only secrets.',
    '',
    'Return this exact JSON shape:',
    '{ "files": [{ "path": "src/components/Header.jsx", "language": "jsx", "content": "complete file content" }], "contracts": [], "warnings": [] }',
    '',
    'Generate only the requested target files. Preserve exact paths. Return complete working file contents. Do not use placeholder comments or TODO-only code. Ensure imports refer to generated or existing files.',
    '',
    'Specification:',
    JSON.stringify(specification, null, 2),
    '',
    'Blueprint:',
    JSON.stringify(blueprint, null, 2),
    '',
    'Previously generated files:',
    JSON.stringify(previousFiles?.map((file) => ({ path: file.path, language: file.language })), null, 2),
    '',
    'Target files:',
    JSON.stringify(targetFiles, null, 2),
    '',
    'Registered contracts:',
    JSON.stringify(contracts || [], null, 2),
    '',
    'Previous warnings:',
    JSON.stringify(warnings || [], null, 2)
  ].join('\n');
}
