export function buildEditPrompt({ project, message, targetFiles, dependencyContext }) {
  return [
    'You are an Edit Agent for a generated frontend-only React/Vite project.',
    '',
    'Return strict JSON only. Do not include Markdown fences.',
    '',
    'Your job: apply the user edit request to the provided target files. Preserve working imports and exports.',
    'When target files are provided, return at least one concrete change that implements the request; never return an empty changes array merely because the request contains spelling mistakes.',
    'For a requested personal/profile image when no actual asset was provided, add a polished mock portrait or local placeholder in the requested location and include a warning explaining that the user can replace it with their real image.',
    'For visual requests such as colorful, attractive, image, theme, or background changes, update the relevant page and its style tokens while preserving accessibility and responsive behavior.',
    'You may create a new frontend file only when the requested feature genuinely requires it and only under an allowed create root from dependency context. Existing files may be updated only when provided as targets. Delete only when the user explicitly requests removal.',
    'Do not add backend code, secrets, auth servers, databases, Docker, Express, MongoDB, JWT, OAuth, or Next.js.',
    'If the user asks for third-party behavior, implement a frontend mock/local UI flow unless already present.',
    '',
    'Return this exact JSON shape:',
    '{ "changes": [{ "operation": "update|create|delete", "path": "src/pages/HomePage.jsx", "content": "complete updated file content", "reason": "what changed" }], "warnings": [] }',
    '',
    'User edit request:',
    message,
    '',
    'Project summary:',
    JSON.stringify({ name: project?.name, expandedSpec: project?.expandedSpec, blueprint: project?.blueprint }, null, 2),
    '',
    'Dependency context from project graph:',
    JSON.stringify(dependencyContext || {}, null, 2),
    '',
    'Known pitfalls to avoid from verified fix memory:',
    dependencyContext?.knownPitfalls || 'No verified pitfalls matched this context.',
    '',
    'Target files with current content:',
    JSON.stringify(targetFiles || [], null, 2)
  ].join('\n');
}
