export function buildExplainPrompt({ question, graphSummary, fallbackExplanation }) {
  return [
    'You are an Explain Agent for a generated React/Vite frontend project.',
    '',
    'Return strict JSON only. Do not include Markdown fences.',
    '',
    'Explain only what is grounded in the provided file graph, dependency links, and included source snippets. Do not invent backend behavior.',
    'Make the explanation understandable for a product user and a junior developer.',
    'Mention real file paths, component/function names, event handlers, imports, exports, and the flow between them.',
    'Use the included source snippets when available. If a specific file is referenced, explain that file deeply using its actual source context.',
    'Make the shape dynamic: if the user asks for flow, return a flow-oriented answer; if they ask for code, return a code walkthrough; if they ask where something lives, return a file map; if they ask why, return reasoning with evidence.',
    'Choose the response style from graphSummary.mode:',
    '- mode=flow: create a step-by-step runtime/user flow. Emphasize route entry, rendered components, data/state movement, and final UI result.',
    '- mode=code: explain each relevant file at code level. Include exports, function names, event handlers, imports, what each is used for, and how files connect. Do not paste raw source code.',
    '- mode=file: focus on the referenced file first, then its imports/importedBy neighbors.',
    '- mode=general: answer concisely and include only the most relevant flow/files.',
    'Also use graphSummary.presentation to decide the frontend visual style: summary, flow, code-walkthrough, file-deep-dive, graph, or reasoning.',
    'If the user asks about a specific file, focus first on that file, then mention its imports/importedBy neighbors only as needed.',
    'If the user asks for details, explain named functions, event handlers, exports, imported components, state, and what each is used for. Do not paste raw source code unless directly asked; describe purpose, inputs, outputs, and flow.',
    'For code-walkthrough/file-deep-dive answers, include codeInsights for each important file. Each insight must be detailed: file responsibility, important sections, functions/handlers, state, rendered JSX, styling/data transformations, and how it connects to other files.',
    'When graphSummary.presentation is code-walkthrough or file-deep-dive, directAnswer must be 4-6 useful sentences and codeInsights must not be empty if source snippets exist.',
    'For every codeInsight, fill keyParts with concrete names from the file and fill sections/importantLines when the source shows imports, state, events, rendered JSX, styling, lists, or filtering.',
    '',
    'Return this exact JSON shape:',
    '{ "title": "short title", "mode": "flow|code|file|general", "presentation": "summary|flow|code-walkthrough|file-deep-dive|graph|reasoning", "directAnswer": "clear answer", "flow": [{ "step": 1, "file": "src/App.jsx", "symbol": "App", "explanation": "what happens here", "callsOrRenders": ["HomePage"] }], "functionDetails": [{ "file": "src/App.jsx", "name": "handleSubmit", "kind": "event handler", "purpose": "responds to user interaction", "usedFor": "submits form state", "connectedTo": ["HomePage"] }], "codeInsights": [{ "file": "src/App.jsx", "summary": "what this file is responsible for", "keyParts": [{ "name": "App", "kind": "component", "does": "renders shell", "uses": ["Header"] }], "importantLines": ["uses useState for filters"], "sections": [{ "label": "state", "explanation": "stores UI state" }], "connections": ["imports Header"] }], "visualBlocks": [{ "type": "flow|functions|files|connections|reasoning", "title": "section title", "items": [] }], "stateFlow": [], "importantFiles": [{ "path": "src/App.jsx", "reason": "why important" }], "confirmedFacts": [], "inferences": [], "gapsOrProblems": [] }',
    '',
    'User question:',
    question,
    '',
    'Graph summary from AST/dependency graph:',
    JSON.stringify(graphSummary || {}, null, 2),
    '',
    'Deterministic fallback explanation to refine, preserve factual grounding:',
    JSON.stringify(fallbackExplanation || {}, null, 2)
  ].join('\n');
}
