export function buildGenerationRepairPrompt({ specification, blueprint, previousFiles, targetFiles, generatedFiles, validationError, contracts, warnings, agentName, phase, dependencyContext, attempt }) {
  return [
    'You are the Generation Repair Agent for a frontend-only React Vite project.',
    '',
    'Return strict JSON only. Do not include Markdown fences.',
    '',
    'Your job is to repair a failed generation batch. The previous agent output did not satisfy validation.',
    'You must return complete file contents for every expected target file that is missing or broken.',
    'Preserve working files from the failed output when possible, but correct imports/exports/content so validation passes.',
    '',
    'Repair attempt: ' + (attempt || 1),
    'Failed agent: ' + (agentName || 'Code Generation Agent'),
    'Phase: ' + (phase || 'code_generation'),
    '',
    'Hard requirements:',
    '- Return this exact JSON shape: { "files": [{ "path": "src/index.css", "language": "css", "content": "complete file content" }], "contracts": [], "warnings": [] }',
    '- Include every expected target file listed below. Do not omit any target.',
    '- Use exact target paths. Do not invent backend/server files.',
    '- Fix relative imports so every ./ import resolves to an existing generated or previous file.',
    '- React components that are imported as default must have a default export.',
    '- Keep the stack frontend-only: React, Vite, JavaScript, Tailwind CSS, React Router when useful, Lucide React.',
    '- Do not add Express, MongoDB, Next.js, auth servers, JWT, Docker, or secret/env access.',
    '',
    'Validation error to fix:',
    String(validationError || ''),
    '',
    'Expected target files:',
    JSON.stringify(targetFiles || [], null, 2),
    '',
    'Failed generated files from this batch:',
    JSON.stringify(generatedFiles || [], null, 2),
    '',
    'Previously generated files available to import:',
    JSON.stringify((previousFiles || []).map((file) => ({ path: file.path, language: file.language, content: String(file.content || '').slice(0, 30000) })), null, 2),
    '',
    'Registered contracts:',
    JSON.stringify(contracts || [], null, 2),
    '',
    'Dependency context:',
    JSON.stringify(dependencyContext || {}, null, 2),
    '',
    'Known warnings/pitfalls:',
    JSON.stringify(warnings || [], null, 2),
    '',
    'Specification:',
    JSON.stringify(specification || {}, null, 2),
    '',
    'Blueprint:',
    JSON.stringify(blueprint || {}, null, 2)
  ].join('\n');
}
